services:
  db:
    image: mysql:8.0
    container_name: online-courses-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT_EXPOSE}:${MYSQL_PORT}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build: .
    container_name: online-courses-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - PORT=${PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
  
