version: "3.9"

services:
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

networks:
  app-network:
    driver: bridge
